### PR TITLE
BUG: Handle null chunks in webpack stats object.

### LINKED ISSUE #110: BUG: Webpack stats object failing type validation (`Cannot load module/asset sizes.`)
I'm making the jump from v0.4.0 to ^3.0.0 and when I run my application I get the following display where the application is built, but the module/asset sizes (and problems when available) are blocked from display due to errors. I checked into some similar issues (e.g. #182) in other posts, but most of them discuss development in dependencies like `inspectpack`, etc. that have since completed, so I'm at a loss.

While webpack is kind of new to me, I'm pretty comfortable saying that the below config is a bit _expansive_ so please let me know what additional or focused information I could supply to help track this issue down. Thanks!

====================================================================

###### If the issue is visual, please provide screenshots here
image

====================================================================

###### Steps to reproduce the problem

====================================================================

###### Please provide a gist of relevant files

Entry script:
```
ENABLE_SOURCE_MAPS=true NODE_ENV=development webpack-dashboard -- webpack-dev-server --config webpack.config.local-dev.js --host 0.0.0.0 --no-inline
```

webpack.config.js
```
REDACTING PER MANAGEMENT :/ Let me know if there is less complete information I can share in support of finding a solution here!
```

====================================================================

###### More Details

- What operating system are you on? Mac OS
- What terminal application are you using? Terminal
- What version of webpack-dashboard are you using? @^3.0.0
- What is the output of running `echo $TERM`? xterm-256color

### PR DESCRIPTION
**Pull request by ryan-roemer**
- Expand type to allow `null` and handle in code. Fixes #110 
- Add regression tests.

@westbrook-asapp - If you have a moment, want to try this one out? (No worries if not, I'm pretty sure this fixes the issue as your stats file now is parseable with this change. Thanks again so much for generating it -- it dramatically reduced the amount of time needed to fix this!)

/cc @parkerziegler

### CODE REVIEW

**Comment by westbrook-asapp** [comment]
I'd be happy to test this out. What's a good way to push this into the workflow? I checked for an `@next` but other than that, being it's a dependency of a dependency, I'm not 100% sure the steps to test this.

**Comment by ryan-roemer** [comment]
@westbrook-asapp -- Good point. I think I'll just release tomorrow and we can test it then 😛 

(You could check it out, build the TS to JS, and manually drop into `node_modules` alone -- no other deps for inspectpack have changed -- but no need if a hassle)

**Comment by parkerziegler** [comment]
@ryan-roemer if you want to release a new version of `inspectpack` with this fix I'd be happy to push out an alpha version of `3.0.2` for `webpack-dashboard` to confirm it does indeed fix things for @westbrook-asapp. Probably wouldn't get to it until later tonight // tomorrow morning, but definitely doable!

**Comment by ryan-roemer** [comment]
I yolo-ed it. Released in `inspectpack@4.2.1`

**Comment by parkerziegler** [comment]
Nice! @westbrook-asapp, I'll get a patch version of `webpack-dashboard` out early tomorrow and ping here so you can install it and test. Thanks a ton @ryan-roemer 💯!

**Comment by westbrook-asapp** [comment]
I can report that early signs here are very positive via a manual copy/paste of the inspectpack code @4.2.1. Look forward to the real thing in the morning. Thanks for you hard work on this, gentlemen.

**Comment by parkerziegler** [comment]
@westbrook-asapp v3.0.2 of `webpack-dashboard` was just published. Let us know if it fixes your issue! Thanks for your help on this.

**Comment by westbrook-asapp** [comment]
This is working great on my end, thank you all!

**Pull request merged**
