### PR TITLE
Add yarn.lock

### PR DESCRIPTION
**Pull request by tptee**

### CODE REVIEW

**Comment by tptee** [comment]
Failed because node < 4 doesn't support yarn, thoughts?

**Comment by ryan-roemer** [comment]
@tptee -- What does webpack currently support node engine-wise?

**Comment by tptee** [comment]
```
"engines": {
  "node": ">=4.3.0 <5.0.0 || >=5.10"
}
```

Looks like they dropped support for less than the previous LTS...

**Comment by ryan-roemer** [comment]
You can drop <4 versions in Travis _and_ if you'ld like ticket out converting code to Node 4-compatible ES6 stuff.

But release is a major once we do this. (And that's fine).

**Pull request merged**
